baseURL = "https://krähenbeisser.de/"
languageCode = "de"
defaultContentLanguage = "de"
title = "Krähenbeißer"
theme = ["projektemacher-base", "aether"]
disableKinds = ["term", "taxonomy"]
publishDir = "docs"
canonifyurls = true
#paginate = 3
description = "Historische Abbildungen von Krähenbeißern"
copyright = "Krähenbeißer"

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["geojson", "gjson"]

[outputFormats]
  [outputFormats.geojson]
    mediaType = "application/json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true

[markup.goldmark.renderer]
  unsafe= true

[module]
  [[module.mounts]]
    source = "assets/js"
    target = "assets/js"

  [[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"

  [[module.mounts]]
    source = "assets/images"
    target = "assets/images"
