baseURL = "https://krähenbeisser.de/"
languageCode = "de"
defaultContentLanguage = "de"
title = "Krähenbeißer"
theme = ["projektemacher-base", "aether"]
disableKinds = ["term", "taxonomy"]
publishDir = "docs"
canonifyurls = true
#paginate = 3
description = "Historische Abbildungen von Krähenbeißern"
copyright = "Krähenbeißer"
enableGitInfo = true

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["geojson", "gjson"]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.geojson]
    mediaType = "application/json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true


  [outputFormats.iiif-manifest]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

  [outputFormats.iiif-collection]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "collection"
    notAlternative = true

[markup]
  defaultMarkdownHandler = 'goldmark'

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe= true

    [markup.goldmark.extensions]
        #typographer = true
        attribute = true
        strikethrough = true

  [markup.goldmark.extensions.typographer]
          apostrophe = '&rsquo;'
          disable = false
          ellipsis = '&hellip;'
          emDash = '&mdash;'
          enDash = '&ndash;'
          leftAngleQuote = '&laquo;'
          leftDoubleQuote = '&ldquo;'
          leftSingleQuote = '&lsquo;'
          rightAngleQuote = '&raquo;'
          rightDoubleQuote = '&rdquo;'
          rightSingleQuote = '&rsquo;'

  [markup.goldmark.extensions.extras]
      [markup.goldmark.extensions.extras.insert]
          enable = true
      [markup.goldmark.extensions.extras.mark]
          enable = true
      [markup.goldmark.extensions.extras.subscript]
          enable = true
      [markup.goldmark.extensions.extras.superscript]
          enable = true

[sitemap]
  changeFreq = 'weekly'

[module]
  [[module.mounts]]
    source = "assets/js"
    target = "assets/js"

  [[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"

  [[module.mounts]]
    source = "assets/images"
    target = "assets/images"

[build]
  writeStats = true
