baseURL = "https://krähenbeisser.de/"
languageCode = "de-de"
defaultContentLanguage = "de"
title = "Krähenbeißer"
theme = "aether"
disableKinds = ["term", "taxonomy"]
publishDir = "docs"
#canonifyurls = true
#paginate = 3

[params]
brand = "Krähenbeißer"
#brand_logo = "images/kraehenbeisser.svg"
description = "Historische Abbildungen von Krähenbeißern"
#homeimg = ""
bgimg = "images/bg.png"
errorimg = "images/kraehenbeisser.svg"
rssinmenu = true

[taxonomies]
Buch = "books"

[module]
[[module.mounts]]
source = "../node_modules/tify/dist"
target = "assets/js/tify"
