baseURL = "https://krähenbeisser.de/"
languageCode = "de-de"
defaultContentLanguage = "de"
title = "Krähenbeißer"
theme = "aether"
disableKinds = ["term", "taxonomy"]
publishDir = "docs"
canonifyurls = true
#paginate = 3
description = "Historische Abbildungen von Krähenbeißern"

[params]
  brand = "Krähenbeißer"
  #brand_logo = "images/kraehenbeisser.svg"
  description = "Historische Abbildungen von Krähenbeißern"
  errorimg = "images/kraehenbeisser.svg"
  rssinmenu = true
  author = "Christian Mahnke"
  keywords = "Krähenbeißer, Krajebieter, Kurische Nehrung, Kurisches Haff, Curonian Lagoon, Curonian Spit"
  stylesheets = ["https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap"]

[markup.goldmark.renderer]
  unsafe= true

[module]
  [[module.mounts]]
    source = "assets/js"
    target = "assets/js"

  [[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"

  [[module.mounts]]
    source = "assets/images"
    target = "assets/images"

  [[module.mounts]]
    source = "node_modules/ol"
    target = "assets/css/ol"

  [[module.mounts]]
    source = "node_modules/normalize.css"
    target = "assets/css/normalize"
