baseURL = "https://krähenbeisser.de/"
languageCode = "de"
defaultContentLanguage = "de"
title = "Krähenbeißer"
theme = ["projektemacher-base", "aether"]
disableKinds = ["term", "taxonomy"]
publishDir = "docs"
canonifyurls = true
#paginate = 3
description = "Historische Abbildungen von Krähenbeißern"
copyright = "Krähenbeißer"

[params]
  brand = "Krähenbeißer"
  #brand_logo = "images/kraehenbeisser.svg"
  description = "Historische Abbildungen von Krähenbeißern"
  errorimg = "/images/kraehenbeisser.svg"
  rssinmenu = true
  author = "Christian Mahnke"
  keywords = "Krähenbeißer, Krajebieter, Kurische Nehrung, Kurisches Haff, Curonian Lagoon, Curonian Spit"
  stylesheets = []
  copyrightYears = "MMXXI"
  cc = false

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["geojson", "gjson"]

[outputFormats]
  [outputFormats.geojson]
    mediaType = "application/json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true

[markup.goldmark.renderer]
  unsafe= true

[module]
  [[module.mounts]]
    source = "assets/js"
    target = "assets/js"

  [[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"

  [[module.mounts]]
    source = "assets/images"
    target = "assets/images"
